### ISSUE TITLE
Error syncing the wallet when tx is pending

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#117]
When trying to sync the wallet with a pending transaction, the following error appears and the transactions view breaks:

`flutter: Error syncing the Wallet type 'HashInfo' is not a subtype of type 'ValueTransferInfo' in type cast
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'HashInfo' is not a subtype of type 'ValueTransferInfo' in type cast
#0      ApiExplorer.getVtt (package:witnet_wallet/bloc/explorer/api_explorer.dart:230:19)
<asynchronous suspension>
#1      ExplorerBloc.syncWalletRoutine (package:witnet_wallet/bloc/explorer/explorer_bloc.dart:156:11)
<asynchronous suspension>
#2      ExplorerBloc._syncWalletEvent (package:witnet_wallet/bloc/explorer/explorer_bloc.dart:86:7)
<asynchronous suspension>
#3      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:226:13)
<asynchronous suspension>`

**Comment by aesedepece** [comment]
Is this still happening?

**Comment by Tommytrg** [comment]
closed #119
