### ISSUE TITLE
Decide release strategy

### ISSUE THREAD

**Issue by Tommytrg** [witnet/my-wit-wallet#129]
what are the different release stages we are going to follow to distribute the light wallet (closed beta, beta, production...)

**Comment by drcpu-github** [comment]
Does a closed beta stage make sense given that anyone can already download the wallet anyway?

**Comment by aesedepece** [comment]
> Does a closed beta stage make sense given that anyone can already download the wallet anyway?

In this context, "closed beta" means that the app can be installed from the Play Store but the link is invite-only. This allows us to get familiar with the process of getting releases delivered to the Play Store even before undergoing the review process for a proper public listing.

**Comment by aesedepece** [comment]
@parodyBit is this somehow decided?

**Comment by aesedepece** [comment]
It is now clear that we're going with closed beta for now and depending on feedback etc. we'll be able to set a roadmap for an eventual public release.
