### ISSUE TITLE
Latest address has disapeared

### ISSUE THREAD

**Issue by Tommytrg** [witnet/my-wit-wallet#161]
![image](https://github.com/witnet/my-wit-wallet/assets/24905681/4923867d-31e3-4016-b291-c1b6d1907146)

Next to copy button should appear the latest address

**Comment by aesedepece** [comment]
I know @parodyBit was working on this. Selecting the last address breaks a few things in the UI.

**Comment by gabaldon** [comment]
closed by [#167](https://github.com/witnet/my-wit-wallet/pull/167=)
