### ISSUE TITLE
Incorrect app title on Android

### ISSUE THREAD

**Issue by drcpu-github** [witnet/my-wit-wallet#168]
When switching between apps on Android, the title on top of the app window is `Material...`, which is presumably the shorthand for `MaterialUI`. This should obviously be `myWitWallet`.

![app_switch](https://github.com/witnet/my-wit-wallet/assets/65105305/42f81774-c3ea-4e6b-8359-dce8c3db93d0)

**Comment by aesedepece** [comment]
Is that on the latest 0.0.3 release? My phone does indeed show the right name in the app switcher.

**Comment by drcpu-github** [comment]
Yes, just installed that release. I added a screenshot to clarify what I mean.

**Comment by aesedepece** [comment]
Wow that's funny. It was `myWitWallet` for me during a few minutes, but then it changed to `Material App` after closing and opening again:
![image](https://github.com/witnet/my-wit-wallet/assets/1316439/dd2beed5-8767-4a43-b470-4ddb550983a0)

**Comment by drcpu-github** [comment]
A good old Heisenbug, it only happens when observed (for a lenghty amount of time). 😄

**Comment by aesedepece** [comment]
Fixed by #174
