### ISSUE TITLE
Start App Approval process on both IOS/Android

### ISSUE THREAD

**Issue by aeweda** [witnet/my-wit-wallet#232]
- Android
  - [ ] Fix prelaunch report errors
  - [x] Disable Internal Track
  - [x] Release another version on Team Lane
- IOS
  - [x] Build & Sign locally with Xcode
  - [x] Upload to Testflight

**Comment by aesedepece** [comment]
@parodyBit can we upload a new version with the fix?

**Comment by Tommytrg** [comment]
@aesedepece @aeweda @parodyBit this issue is blocked by https://github.com/witnet/my-wit-wallet/issues/252
