### ISSUE TITLE
Discuss Windows Signing Certificate

### ISSUE THREAD

**Issue by aeweda** [witnet/my-wit-wallet#247]

**Comment by Tommytrg** [comment]
If we want to add a certificate for the Windows release, we have some options:
- Use the free certificate offered by Windows, but this release can only be distributed in the Windows store.
- Pay a company like DigiCert, which provides a Code Signing Certificate.

The main benefit of using a certificate is that we can release the wallet as a `.msix`, but we have agreed that the cost of this certificate is not worth it.
