### ISSUE TITLE
Assess the flows we have to test e2e

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#267]

**Comment by gabaldon** [comment]
List of flows we have to test e2e:
https://www.notion.so/witnet/myWitWallet-list-of-e2e-flows-to-test-869c75dac4f946a887d8b243b4fa03ac

**Comment by Tommytrg** [comment]
Epic with the proposed flows: https://github.com/witnet/my-wit-wallet/issues/353
