### ISSUE TITLE
UI: Allow importing a single address

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#273]
Import:
- [x]  Add switch when importing a wallet to import  a HD wallet (standard wallet) or a single address that can be use for node operators.
- [x] When the single address wallet switch is toggle, import from non encrypted XPRV.
- [x] Update copies:
```
Title: Import wallet from an Xprv key.
Xprv is a key exchange format that encodes and protects your wallet with a password. 
Xprv keys look like a long sequence of apparently random letters and numbers, preceded by "xprv".
To import your wallet from a node master key, you need to type the key itself and click continue.
To import your wallet from an Xprv key, encrypted with a password,
you need to type the key itself and its password below:
```
Receive screen:
- [x] Avoid generating new address if the type is single address wallet.
Export:
- [x] When single address wallet, avoid exporting XPRV with password.

Dashboard screen:

- [x] When importing a node single address wallet, show mint transactions.
- [x] Implement ui for showing wallet type:

<img width="498" alt="Screenshot 2023-07-11 at 10 19 37" src="https://github.com/witnet/my-wit-wallet/assets/16032491/2498d920-6fe3-4d70-a2d1-6c0f96a3f63e">

<img width="471" alt="Screenshot 2023-07-11 at 10 59 26" src="https://github.com/witnet/my-wit-wallet/assets/16032491/b5628422-c78a-4277-a369-9cd3bd76bcc5">

**Comment by aesedepece** [comment]
The standard BIP-32 compliant wallet type is often referred as `HD Wallet` in many other wallet software. If someone is not familiar with the term, a single Google search will show them dozens of millions of articles explaining what they are and what's their point.

Then, I think it's important that when you are importing or creating a wallet, in the part where you need to choose the wallet type, "HD Wallet" is presented as "HD Wallet (recommended)", and the other option shall be "Single-address (e.g. from witnet-rust)".
