### ISSUE TITLE
Error loading wallets when initializing the app

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#340]
When closing and opening the deployed app with one or more wallets imported, sometimes, the login screen is not rendered.

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/my-wit-wallet/340?planning-poker) with Zenhub @aesedepece @gabaldon @guidiaz @aeweda
