### ISSUE TITLE
(IOS) Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by parodyBit** [witnet/my-wit-wallet#344]
the app does not use push notifications, this is a bug.
We don't have to implement any publish notification features, just simply enable the feature and capability will suppress the warning.

ITMS-90078: 
described here: https://github.com/flutter/flutter/issues/14182

**Comment by gabaldon** [comment]
I would not enable push notification if we are not going to use them in the near future. The warning should be ignored till the issue https://github.com/flutter/flutter/issues/14182 is fixed.
