### ISSUE TITLE
Show a snackbar when transaction is deleted

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#395]
When a pending transaction is not `mined`, it results in `unknown hash`. Currently, the `unknown hash` VTTs are deleted from the transactions list. In this case, the user should see a snackbar explaining that the transaction has been removed from the transactions list because it was not mined.

**Comment by aesedepece** [comment]
Would that be shown after a timeout? (i.e. if the transaction is not `mined` after X minutes)

**Comment by parodyBit** [comment]
> Would that be shown after a timeout? (i.e. if the transaction is not `mined` after X minutes)

anytime the next sync returns `unknown hash` for a pending transaction.
currently this happens when a user does a new priority-replace-by-fee transaction using the same UTXOs, 

does a "timeout" remove a pending transaction from the mempool? if so then yes.

**Comment by aesedepece** [comment]
> does a "timeout" remove a pending transaction from the mempool? if so then yes.

No, it doesn't. I was just trying to understand the assumptions here.

Are you saying that the explorer backend only gives `unknown hash` for transactions that have been dropped from the mempool by means of their UTXOs being spent in a different transaction? (in addition to the case of non-existing transaction hashes)

If that is the case, then the proposed snackbar makes sense to me. If not, I'm afraid of flagging a transaction as failed, but then seeing it getting confirmed.

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/my-wit-wallet/395?planning-poker) with Zenhub @aesedepece @gabaldon @guidiaz @aeweda

**Comment by gabaldon** [comment]
This issue is no longer needed due to the implementation of https://github.com/witnet/my-wit-wallet/pull/409.
This pr avoids reusing the UTXOS to create a new transaction. The only way to reuse the existing UTXOS is to accelerate the transaction. In this case, the previous transaction is deleted from the transaction list and replaced by the accelerated transaction. The user will know that the replacement is due to the sending of an accelerated transaction, so there is no need to show a snack bar explaining the disappearing transaction.
