### ISSUE TITLE
Show modal to download new version in desktop

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#398]
The desktop version does not include an auto update feature, currently the user needs to download the new version and replace the current one.

We should show a modal when a new version is released, this modal will include a link to download the new one, or add a library to detect a new version is released.

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/my-wit-wallet/398?planning-poker) with Zenhub @aesedepece @gabaldon @guidiaz @aeweda
