### ISSUE TITLE
Avoid top bar overlap step bar 

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#414]
The rounded bottom border overlaps with the step bar. The step bar is visible but cannot be clicked.

<img width="417" alt="Screenshot 2023-10-23 at 09 15 36" src="https://github.com/witnet/my-wit-wallet/assets/16032491/721d64b1-2dd7-41d8-bc5f-0a2047e79698">

**Comment by Tommytrg** [comment]
Closed by #420
