### ISSUE TITLE
Fill form to add android > 11 external storage permissions

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#448]
Android versions above 11 need MANAGE_EXTERNAL_STORAGE [permissions](https://pub.dev/packages/permission_handler#faq), that requires to further actions in [Google Play](https://support.google.com/googleplay/android-developer/answer/9214102).

**Comment by Tommytrg** [comment]
In the end, we could  save files the in the downloads folder without adding the external storage permissions.
