### ISSUE TITLE
No possibility to import anything (wallet)

### ISSUE THREAD

**Issue by Imonda** [witnet/my-wit-wallet#479]
No possibility to import wallet. It can't be more scroll down, there is a part of the button but not clickable.
myWitWallet 0.2.2-dev 
Win 11 PRO.
1920x1080

![Screenshot 2023-11-30 171937](https://github.com/witnet/my-wit-wallet/assets/666361/f100563d-cb4a-4e18-a004-bd1395275320)

**Comment by Imonda** [comment]
I've just found the only way to import the wallet. You can use the arrow keys on the keyboard to select the Import button, and then somehow proceed through the seed, because the rest is not visible on the screen.

**Comment by gabaldon** [comment]
myWitWallet for Windows has been built with the new version of Flutter. This breaks some UI components and theme properties. As soon as [issue 450](https://github.com/witnet/my-wit-wallet/issues/460) is finished, we will release a new version that fixes this bug.

**Comment by Tommytrg** [comment]
@Imonda myWitWallet@1.0.1 has been released. Could you confirm that the reported bug is fixed?

**Comment by Imonda** [comment]
@gabaldon - Yes, thank you, everything works great.
