### ISSUE TITLE
App freezes after login on Ubuntu

### ISSUE THREAD

**Issue by parodyBit** [witnet/my-wit-wallet#480]
The app starts and the user is able to login, it shows the correct balance but then just freezes
`(myWitWallet:11439): Gdk-CRITICAL **: 15:53:16.634: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
Trace/breakpoint trap (core dumped)`

```
Distributor ID: Ubuntu
Description: Ubuntu 22.04.3 LTS
Release: 22.04
Codename: jammy
```

**Comment by Tommytrg** [comment]
Ensure this error is still happening with the latest version of mww on ubuntu

**Comment by parodyBit** [comment]
Seems to be working fine with the latest version of myWitWallet and Ubuntu 22.04.3 LTS

![VirtualBox_ubuntu_20 4 3_16_01_2024_07_54_56](https://github.com/witnet/my-wit-wallet/assets/58690522/fb3e52b8-18e5-4725-b332-7eade1ce564a)
