### ISSUE TITLE
Design new header

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#590]
Header of myWitWallet requires a redesign:

![Screenshot 2024-10-07 at 10 05 38](https://github.com/user-attachments/assets/2987fdb5-ba00-423c-8d3e-3b6dcf4cfa72)

**Comment by gabaldon** [comment]
https://www.figma.com/design/8bhyRGf88LcbELaWmYZnHQ/myWitWallet-header-redesign?node-id=0-1&t=IBdTZRq6uUQTHxNX-1

**Comment by Tommytrg** [comment]
Final version:

<img src="https://github.com/user-attachments/assets/74313f89-1da7-4d61-b32b-28f42f668c0f" width="250">
<img src="https://github.com/user-attachments/assets/9bf8922b-17a4-42e9-b8eb-27bef402e2d4" width="250">
<img src="https://github.com/user-attachments/assets/128f04a6-5d41-48e5-928d-7cdf911f3ca6" width="250">
