### ISSUE TITLE
Update Nimbus Mono

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#606]
For the combination of caracters fi, the Nimbus Mono does not apply the mono type. Also, the baseline is different from the rest of the fonts, so it aligns different than the rest. 
The Nimbus Mono font should be updated or fixed.

**Comment by aesedepece** [comment]
https://fonts.google.com/specimen/Courier+Prime?query=Courier+Prime&categoryFilters=Appearance:%2FMonospace%2FMonospace

**Comment by gabaldon** [comment]
closed by https://github.com/witnet/my-wit-wallet/commit/fe0f4b0e2018194963b165eca4f9cc349ed7786f
